Amend pra botar mudanças no Dockerfile do Flask

diff --git a/DOCKER/flask/dockerfile b/DOCKER/flask/dockerfile
--- a/DOCKER/flask/dockerfile
+++ b/DOCKER/flask/dockerfile
@@ -30,7 +30,7 @@ RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r re
 
 # Copy application files
 COPY ./FLASK ./
-COPY ./env.csv ./
+COPY ./.env ./
 
 
 FROM python:3.9-slim-bullseye AS runner_flask
@@ -57,7 +57,7 @@ RUN apt-get update -y \
 
 # Verify required files exist
 RUN test -f ./permalink-googleDrive-pibiti6-nervo.json || (echo "permalink-googleDrive-pibiti6-nervo.json file not found in FLASK directory" && exit 1)
-RUN test -f ./env.csv || (echo "env.csv file not found in FLASK directory" && exit 1)
+RUN test -f ./.env || (echo ".env file not found in FLASK directory" && exit 1)
 
 # SO PRA TESTAR WEASYPRINT (retirar em producao)
 # RUN weasyprint https://weasyprint.org /tmp/weasyprint-website.pdf
