Mudando nome do diretorio pra flask_backend

diff --git a/DOCKER/flask/dockerfile b/DOCKER/flask/dockerfile
--- a/DOCKER/flask/dockerfile
+++ b/DOCKER/flask/dockerfile
@@ -6,7 +6,7 @@ ENV DEBIAN_FRONTEND=noninteractive
 ENV PIP_DISABLE_PIP_VERSION_CHECK=1
 ENV PYTHONDONTWRITEBYTECODE=1
 ENV PYTHONUNBUFFERED=1
-WORKDIR /FLASK
+WORKDIR /flask_backend
 
 # Install dependencies and clean up
 RUN apt-get update -y && apt-get install -y --no-install-recommends \
@@ -24,24 +24,24 @@ RUN apt-get update -y && apt-get install -y --no-install-recommends \
 RUN python3 -m venv /opt/venv  
 ENV PATH="/opt/venv/bin:$PATH"
 
-COPY FLASK/requirements.txt .
+COPY flask_backend/requirements.txt .
 RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.txt
 
 # Copy application files
-COPY ./FLASK ./
+COPY ./flask_backend ./
 COPY ./.env ./
 
 
 FROM python:3.9-slim-bullseye AS runner_flask
 
-WORKDIR /FLASK
+WORKDIR /flask_backend
 
-# VOLUME ["/FLASK"]
+# VOLUME ["/flask_backend"]
 # Copy the virtualenv from builder
 COPY --from=builder /opt/venv /opt/venv  
 ENV PATH="/opt/venv/bin:$PATH"
 # Copy only necessary files from the builder stage
-COPY --from=builder /FLASK /FLASK
+COPY --from=builder /flask_backend /flask_backend
 
 # Reinstall only runtime libs (no gcc, no weasyprint build deps)
 RUN apt-get update -y \
@@ -54,8 +54,8 @@ RUN apt-get update -y \
     && apt-get clean && rm -rf /var/lib/apt/lists/*
 
 # Verify required files exist
-RUN test -f ./permalink-googleDrive-pibiti6-nervo.json || (echo "permalink-googleDrive-pibiti6-nervo.json file not found in FLASK directory" && exit 1)
-RUN test -f ./.env || (echo ".env file not found in FLASK directory" && exit 1)
+RUN test -f ./permalink-googleDrive-pibiti6-nervo.json || (echo "permalink-googleDrive-pibiti6-nervo.json file not found in flask_backend directory" && exit 1)
+RUN test -f ./.env || (echo ".env file not found in flask_backend directory" && exit 1)
 
 # SO PRA TESTAR WEASYPRINT (retirar em producao)
 # RUN weasyprint https://weasyprint.org /tmp/weasyprint-website.pdf
